/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "register", description = "the register API")
public interface RegisterApi {

    @ApiOperation(value = "Registers a new user", nickname = "register", notes = "Register a new user by obtaining a new license.", tags={ "users", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Detailed license data"),
        @ApiResponse(code = 200, message = "unexpected error") })
    @RequestMapping(value = "/register",
        method = RequestMethod.POST)
    ResponseEntity<Void> register(@NotNull @ApiParam(value = "the users email address", required = true) @Valid @RequestParam(value = "email", required = true) String email);

}
